from snakemake.utils import min_version

min_version("6.10.0")
configfile: "config/config.yaml"

module dna_seq_gatk_variant_calling:
    snakefile:
        github("snakemake-workflows/dna-seq-gatk-variant-calling", path="workflow/Snakefile", tag="v2.1.1")
    config:
        config

use rule * from dna_seq_gatk_variant_calling

