from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling as a module
module dna_seq_gatk_variant_calling:
    snakefile:
        github("snakemake-workflows/dna-seq-gatk-variant-calling", path="workflow/Snakefile", tag="v2.1.1")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling
use rule * from dna_seq_gatk_variant_calling
